import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <nav className="w-full h-16 shadow-md mb-6">
      <div className="w-4/5 mx-auto h-full flex space-x-4">
        <Link className="flex items-center justify-center h-full underline decoration-wavy decoration-blue-500 hover:decoration-blue-700" href="/">Home</Link>
        <Link className="flex items-center justify-center h-full underline decoration-wavy decoration-blue-500 hover:decoration-blue-700" href="/users">Users</Link>
      </div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
